### ISSUE TITLE
Tiles: Can the custom launcher be removed?

### ISSUE THREAD

**Issue by gunnarmorling** [moditect/layrry-examples#2]
@aalmiray, is the custom launcher truly needed, or can the default Layrry launcher be used?

**Comment by aalmiray** [comment]
The reason to use the custom launcher now is for keeping the module versions in sync with the pom dependencies.

**Comment by gunnarmorling** [comment]
Ah, I see. How about solving this via resource filtering (replacing
placeholders in the layers.toml, so to inject variables from Maven)? I'd
like to push users towards the standard launcher as much as possible.

>

**Comment by aalmiray** [comment]
Makes sense. The custom launcher was created before Layrry had value placeholders ;-)

**Comment by gunnarmorling** [comment]
I was even just thinking of the Maven resources plug-in, so Layrry would
process the final layers.toml file; but this sounds even better actually.
How will values be provided then, as arguments to the launcher?

>

**Comment by aalmiray** [comment]
Sure, replace version placeholders using the Maven/Gradle resources plugin, that's better as that's less code inside Layrry ;-)

**Comment by gunnarmorling** [comment]
So thinking more about it, what's the value of the _app/modular-tiles-launcher_ module to begin with? It seems this could just be simply removed entirely; the README shows the instructions for running it via jbang, and we might add instructions for using the Layrry launcher from the local Maven repo, too. WDYT?

**Comment by aalmiray** [comment]
Indeed. The problem I'm facing right now is figuring out the minimum changes required for both Maven & Gradle to produce the layers file with version numbers. See https://github.com/moditect/layrry/issues/45 for additional thoughts, if that feature were to be added then some of the adjustments I'll do to this repo could be removed at a later date as well.

**Comment by gunnarmorling** [comment]
Just commented on #45, but I don't think it's even needed for tackling this issue here; for that, I'd suggest the following:

* remove _app/modular-tiles-launcher_ and related instructions in _README.md_
* make _layers.toml_ subject to Maven resource filtering for injecting the version properties, e.g. by moving it to _src/main/resources_ of the root dir (same for Gradle)
* update _jbang_ call in _README.md_ to refer the filtered _layers.toml_ file

Would that work?

**Comment by aalmiray** [comment]
Yes, but take into account that instructions for generating and copying tile plugins are also currently located in the launcher project. Those instructions need to move to the root as well.

**Comment by gunnarmorling** [comment]
Woohoo, thx!

>
