### ISSUE TITLE
Tiles: Classes not unloaded upon layer removal

### ISSUE THREAD

**Issue by gunnarmorling** [moditect/layrry-examples#3]
I don't observe that classes get unloaded when removing a plug-in layer. Whereas with the Vert.x demo, that's the case. I suppose a reference to the layer or its classes is kept from the core layer, so they don't become eligible for GC. // CC @aalmiray.

**Comment by aalmiray** [comment]
Could it be the `PluginRegistry` or JavaFX's scene graph?

**Comment by gunnarmorling** [comment]
`PluginRegistry` was my first suspect, but it seems ok from a quick glimpse. Scene graph could also be it, that's beyond my pay grade, though ;) That definitely needs further examination. I'm running with `-XX:G1PeriodicGCInterval=5000` on JDK 12+, which regularly runs a GC in the background which normally should take care of any classes not referenced any longer.

**Comment by gunnarmorling** [comment]
<img width="1552" alt="Screen Shot 2020-10-10 at 11 29 06" src="https://user-images.githubusercontent.com/28612/95651613-e0339000-0aeb-11eb-9f88-63510a585d9e.png">

Ok, so false alert; I hadn't enabled the class unloading event type in JFR when looking into this, *doh*. Now that I have that, I see the classes of removed plug-ins being unloaded upon the periodic GC, as it's expected. All good :)

**Comment by aalmiray** [comment]
Phew, you've got me worried for a picosecond ;-)
