### ISSUE TITLE
Tiles: Leaking threads and thus leaking classloaders

### ISSUE THREAD

**Issue by gunnarmorling** [moditect/layrry-examples#4]
Hey @aalmiray, so it seems there _is_ an issue with leaking resources in the tiles demo after all. After removing all plug-ins, I still see threads named `TileTick` lingering around, and they prevent the layer-specific classloaders to be collected. I tried to add calls to `stop()` to all of the three plug-ins (which should shut down these threads):

```
@Override
protected void cleanup() {
    getTile().setRunning(false);
    getTile().stop();
}
```

But it doesn't make any difference. Any ideas?

**Comment by aalmiray** [comment]
It looks live every tile should call those 2 methods on `cleanup()` by default otherwise their internal ScheduledExecutorService keeps running. That service runs with a ThreadFactory set as daemon btw.

I don't see any direct calls to `setRunning(true)`.

**Comment by aalmiray** [comment]
Pushed a small change, hope this fixes it.

Perhaps @HanSolo has a clue on what may be happening here.

**Comment by gunnarmorling** [comment]
Yeah, so it's looking better now with the call to `stop()`; I had been looking at old plug-in versions still, now with everything re-built, those threads are gone after a plug-in has been removed.

**Comment by aalmiray** [comment]
Yay! No more leaks I hope.

**Comment by gunnarmorling** [comment]
So do I :) Going to test it some more.

**Comment by gunnarmorling** [comment]
Ok, looking good now with the thread removal. Closing. Thanks!
